### ISSUE TITLE
Does not work on windows?

### ISSUE THREAD

**Issue by ThaDafinser** [wichert/po-xls#3]
Hello,

since this is my first ever installed python package, i think i've done something wrong on my side?

But i get this error message:

```
C:\Data\wap\htdocs\data\language>po-to-xls en.po
Writing catalog to sheet  [------------------------------------]    1%
Traceback (most recent call last):
  File "c:\data\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\data\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Data\Python27\Scripts\po-to-xls.exe\__main__.py", line 9, in <module>

  File "c:\data\python27\lib\site-packages\click\core.py", line 700, in __call__

    return self.main(*args, **kwargs)
  File "c:\data\python27\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\data\python27\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\data\python27\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\data\python27\lib\site-packages\poxls\po_to_xls.py", line 119, in mai
n
    sheet.append(row)
  File "c:\data\python27\lib\site-packages\openpyxl\writer\write_only.py", line
185, in append
    raise ValueError
ValueError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\data\python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\data\python27\lib\site-packages\openpyxl\writer\write_only.py", line
39, in _openpyxl_shutdown
    os.remove(path)
WindowsError: [Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie
von einem anderen Prozess verwendet wird: 'c:\\users\\kecmar\\appdata\\local\\te
mp\\openpyxl.ko9s6p'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "c:\data\python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\data\python27\lib\site-packages\openpyxl\writer\write_only.py", line
39, in _openpyxl_shutdown
    os.remove(path)
WindowsError: [Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie
von einem anderen Prozess verwendet wird: 'c:\\users\\kecmar\\appdata\\local\\te
mp\\openpyxl.ko9s6p'
```

The problem seems to be: `Der Prozess kann nicht auf die Datei zugreifen, da sie
von einem anderen Prozess verwendet wird: 'c:\\users\\kecmar\\appdata\\local\\te
mp\\openpyxl.ko9s6p'`

Any ideas?

**Comment by ThaDafinser** [comment]
Closing, due to inactivity

**Comment by wichert** [comment]
FWIW this looks like a bug in OpenPyxel, not po-xls itself. If this still happens I suggest creating an issue in [their issue tracker](http://bitbucket.org/openpyxl/openpyxl/issues)
